# Generated by Django 4.1 on 2022-09-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API',
            new_name='Data',
        ),
    ]
